add_image_number: false
calc_face_sim: false
compare_with: ''
entended_info: false
file_format: ''
file_format_grid: ''
from_file: ''
image_file_pattern: ''
init_img: ''
laion400m: false
ref_prompt: None
ref_prompt_mix_weight: 0.0
scores_csv: None
seed: 88542
skip_grid: false
skip_save: false
