model:
  base_learning_rate: 8e-04
  weight_decay: 0.0

  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    # linear_start/linear_end: params for linear beta schedule.
    beta_schedule: linear
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    # cond_stage_trainable has no effect, as it's checked within ddpm.instantiate_cond_stage().
    # After this call, the model sets requires_grad=False for all params of cond_stage (CLIP encoder) 
    # after seeing unfreeze_model = False.
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_ema
    scale_factor: 0.18215
    use_ema: False
    unfreeze_model: False
    model_lr: 0.0
    use_layerwise_embedding:    True
    use_ada_embedding:          True
    use_fp_trick:               True
    do_clip_teacher_filtering:  True
    num_candidate_teachers:     3
    composition_regs_iter_gap:          3
    # typical loss_static_emb_reg is ~2e-3, * weight -> 4e-8.
    static_embedding_reg_weight:        2e-5
    # typical loss_ada_em_reg is ~5e-2, * weight -> 5e-5.
    ada_embedding_reg_weight:           1e-3
    # typical delta reg loss: 0.85, * weight -> 1.7e-4
    prompt_emb_delta_reg_weight:        4e-4
    padding_embs_align_loss_weight:     0 # disabled. 1e-4
    # typical loss_subj_comp_key_ortho is 0.2, * weight -> 2e-7
    subj_comp_key_ortho_loss_weight:    2e-4 
    subj_comp_value_ortho_loss_weight:  0     # disabled. # 1e-5
    # typical loss_mix_prompt_distill: 4, * weight -> 1.2e-3.
    mix_prompt_distill_weight:          1e-4
    # The scale of subj_attn_norm_distill_loss based on mix_prompt_distill_weight.
    # subj_attn_norm_distill_loss is DISABLED for faces, but enabled for objects.
    subj_attn_norm_distill_loss_base:   0   
    comp_fg_bg_preserve_loss_weight:    1e-3
    sc_mc_bg_match_loss_base:           0.2      # 0 to disable.
    # fg_bg_comple: used in non-wds recon iters.
    # loss_fg_bg_complementary: 1.5,      * weight -> 7.5e-4
    fg_bg_complementary_loss_weight:    1e-4
    # loss_fg_xlayer_consist ~ 0.2, loss_bg_xlayer_consist ~ 0.1. * weight -> 3e-4.
    fg_bg_xlayer_consist_loss_weight:   5e-5
    fg_bg_token_emb_ortho_loss_weight:  1e-4
    compel_cfg_weight_level_range:      [1, 3]
    apply_compel_cfg_prob:              0.5
    # fg_wds_comple: used in wds recon iters.
    fg_wds_complementary_loss_weight:   0 #1e-4
    wds_bg_recon_discount:              0.05
    
    optimizer_type: AdamW      # NAdam     # AdamW or NAdam.
    optimizer_bits: 32         # 8 or 32. 8 bit doesn't save much RAM and performs worse.
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 500
        # max_decay_steps = max_steps = 3500. The final LR is 0.1*base_lr.
        # max_decay_steps and max_steps will be customized in main.py accordingly.
        max_decay_steps: 3500
        lr_start: 0.01
        lr_max:   1.0
        lr_min:   0.1

    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManager
      params:
        placeholder_strings: ["*"]
        initializer_words: ["sculpture"]
        initializer_weights: [ None ]
        num_vectors_per_token: 1
        use_layerwise_embedding: True
        layerwise_lora_rank_token_ratio: 2
        ada_emb_weight: 0.5
        emb_ema_as_pooling_probe_weight: 0.5  # Should be the same as ada_emb_weight.
        ada_use_attn_pooler: True
        specialized_comp_embs_mod: -1
        contrast_fgbg_init_coeff:  0
        attn_postmix_weight: 0
        conv_attn_layerwise_scale_learnable: True
        training_add_noise_std_range:  [ 0.1, 0.4 ]
        # probs for recon_iter and distill_iter, respectively
        training_add_noise_prob:   { 'recon_iter': 0.6, 'distill_iter': 0.4 }

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
          #attn_type: 'none'

        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
        last_layers_skip_weights: [0.5, 0.5]

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 1
    wrap: false
    train:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512       # Image resolution
        set: train
        repeats: 100
        verbose: true
    validation:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512       # Image resolution
        set: val
        repeats: 10
        verbose: true
        
lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 8000     # 8000 > max_steps = 3500, effectively disabling image logger.
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    # max_decay_steps and max_steps will be customized in main.py accordingly.
    max_steps: 3500
    limit_val_batches: 0.0
    grad_clip: 0.5
    
