model:
  base_learning_rate: 8e-04
  weight_decay: 0.0

  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    # linear_start/linear_end: params for linear beta schedule.
    beta_schedule: linear
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    # cond_stage_trainable has no effect, as it's checked within ddpm.instantiate_cond_stage().
    # After this call, the model sets requires_grad=False for all params of cond_stage (CLIP encoder) 
    # after seeing unfreeze_model = False.
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_ema
    scale_factor: 0.18215
    use_ema: False
    embedding_reg_weight: 0.01
    unfreeze_model: False
    model_lr: 0.0
    use_layerwise_embedding: True
    use_ada_embedding: True
    # composition_regs includes prompt_delta_reg and composition_prompt_mix_reg.
    composition_regs_iter_gap: 4
    # typical delta reg loss: 0.75, * weight -> 7.5e-5
    prompt_delta_reg_weight:       1e-4
    # typical prompt mix reg loss: 0.2, * weight -> 2e-5.
    composition_prompt_mix_reg_weight:  1e-4
    filter_with_clip_loss: True
    use_fp_trick:          True

    optimizer_type: AdamW     # sophia
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 500
        # max_decay_steps = max_steps = 4500. The final LR is 0.2*base_lr.
        max_decay_steps: 4500
        lr_start: 0.01
        lr_max:   1.0
        lr_min:   0.25

    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManager
      params:
        placeholder_strings: ["*"]
        initializer_words: ["sculpture"]
        initializer_weights: [ None ]
        # Negative prompts lead to worse images.
        initializer_neg_words: [ ]       
        num_vectors_per_token: 1
        progressive_words: False
        use_layerwise_embedding: True
        layerwise_lora_rank_token_ratio: 2
        ada_emb_weight: 0.5
        ada_use_attn_pooler: True
        # composition_regs alternates between prompt_delta_reg and composition_prompt_mix_reg.
        # So prompt_delta_reg_iter_gap = 2 * composition_regs_iter_gap = 10.
        prompt_delta_reg_iter_gap: 4

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
        last_layer_skip_weight: 0.5

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512       # Image resolution
        set: train
        repeats: 100
    validation:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512       # Image resolution
        set: val
        repeats: 10

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 8000     # 8000 > max_steps = 4500, effectively disabling image logger.
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_steps: 4500
